name: goal-focus-server

services:
  pg:
    image: postgres:latest
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=GoalFocus
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=GoalFocus